### ISSUE TITLE
One error for training FastAttentionXML

### ISSUE THREAD

**Issue by zjcanjux** [yourh/AttentionXML#1]
args=(self.data_cnf['train']['sparse'], self.data_cnf['train']['labels'], mlb),
KeyError: 'sparse'

there's no information about train sparse train labels in /FastAttentionXML-Wiki-500K.yaml file.
Thanks for any help.

**Comment by yourh** [comment]
The data_cnf is from configure/datasets/Wiki-500K.yaml, not FastAttentionXML-Wiki-500K.yaml.

**Comment by zjcanjux** [comment]
> The data_cnf is from configure/datasets/Wiki-500K.yaml, not FastAttentionXML-Wiki-500K.yaml.

Thanks, it means it should be data_cnf from  configure/datasets/Wiki-500K.yaml and model from configure/models/FastAttentionXML-Wiki-500K.yaml, is right?

**Comment by zjcanjux** [comment]
> The data_cnf is from configure/datasets/Wiki-500K.yaml, not FastAttentionXML-Wiki-500K.yaml.

I fix it according your reply, thank you very much, but I get another problem. 

 while not os.path.exists(F'{self.groups_path}-Level-{level}.npy'):
                time.sleep(30)
 groups = np.load(F'{self.groups_path}-Level-{level}.npy')

in your program, how to generate "{self.groups_path}-Level-{level}.npy" file? I run your program, it will still sleep here, because there is no " {self.groups_path}-Level-{level}.npy".

Thanks for any help from you.

**Comment by yourh** [comment]
It will be generated by cluster_process in method "train".

**Comment by zjcanjux** [comment]
> It will generate by cluster_process in method "train".

[I 191114 10:45:48 cluster:23] Clustering
[I 191114 10:45:50 cluster:26] Getting Labels Feature
[I 191114 10:45:51 cluster:28] Start Clustering [13, 16, 19]
[I 191114 10:45:51 cluster:45] Finish Clustering 1
[I 191114 10:45:51 cluster:45] Finish Clustering 2
[I 191114 10:45:52 cluster:45] Finish Clustering 4
[I 191114 10:45:53 cluster:45] Finish Clustering 8
[I 191114 10:45:54 cluster:45] Finish Clustering 16
[I 191114 10:45:55 cluster:45] Finish Clustering 32
[I 191114 10:45:56 cluster:45] Finish Clustering 64
[I 191114 10:45:58 cluster:45] Finish Clustering 128
[I 191114 10:46:00 cluster:45] Finish Clustering 256
[I 191114 10:46:04 cluster:45] Finish Clustering 512
[I 191114 10:46:04 cluster:51] Finish Clustering

Do I need to do something else? I found it still in time.sleep(30) step.  The program will still in "Finish Clustering" and do not go ahead.

**Comment by yourh** [comment]
Did you modify the contents in FastAttentionXML-Wiki-500K.yaml? It seems like the clustering didn't work well for your settings.

**Comment by zhaolulul** [comment]
![image](https://user-images.githubusercontent.com/40298785/92468307-88acb680-f205-11ea-9726-ed1611fb4f39.png)
你好，在构建树的过程中，你只考虑了 ，如果 一个节点还有标签的数据 >max_leaf，那么就 切分节点，这没有问题，可是 如果你没有写else,那么 在 运行 assert sum(len(labels) for labels in labels_list) == labels_f.shape[0]  就会出现问题，因为q已经不包含   <max_leaf的那个节点了。 我出现的问题  和 zjcanjux 出现的问题是一样的

**Comment by zhaolulul** [comment]
另外你的模型文件 FastAttentionXML-Amazon-670K.yaml 里面 cluster 下的levels ，没有考虑到 ，构建树的所有节点个数 < 你设置的层数 （层数对应的节点个数）  会怎么样，你给的模型文件应该是 使用 相应的数据集，使用其他的数据集运行，会出现问题 ，需要自己改代码
