### ISSUE TITLE
Some questions about dataset wiki10-31k and wiki-500k

### ISSUE THREAD

**Issue by Xu-Wave** [yourh/AttentionXML#10]
Excellent work！
1. I know that XMLRepository has these two datasets, but it can not be downloaded now. Can I get the same datasets through your dataset link in your README.md?
2. Can I use your script preprocess code and GloVe embedding for these two datasets？
3. I have emailed you, thanks for replying！
Thank you！！！

**Comment by yourh** [comment]
1. Yes, only the Wiki-500K we used is slightly different because we crawl the raw texts by ourselves and some of them are unavailable.
2. Yes.

**Comment by TaoXuWorkAI** [comment]
Thank you！I have read your code about PLT construction. Can I get your wechat to have a discussion？I have some questions about methods in cluster methods. Please..Thanks!

**Comment by Xu-Wave** [comment]
> 1. Yes, only the Wiki-500K we used is slightly different because we crawl the raw texts by ourselves and some of them are unavailable.
> 2. Yes.

Thank you！I have read your code about PLT construction. Can I get your wechat to have a discussion？I have some questions about methods in cluster methods. Please..Thanks!

**Comment by Xu-Wave** [comment]
Thank you！I have read your code about PLT construction. Can I get your wechat to have a discussion？I have some questions about methods in cluster methods. Please..Thanks!

**Comment by yourh** [comment]
OK, email me your WeChat ID.
