### ISSUE TITLE
Questions about trainning detail

### ISSUE THREAD

**Issue by PLoic** [yourh/AttentionXML#11]
Hi, thanks for your works.

I just have some question, what's are the batch size and number of epochs for the Amazon-670k and Wiki-500K. For the AttentionXML network without PLT. 

Thanks for your answer :)

**Comment by yourh** [comment]
We didn't run AttentionXML without PLT on Amazon-670K and Wiki-500K because these datasets are too large.

**Comment by PLoic** [comment]
Thanks for answering !
