### ISSUE TITLE
Regarding execution time on Amazon-670k dataset

### ISSUE THREAD

**Issue by pnjha** [yourh/AttentionXML#12]
I ran the code for the Amazon-670k dataset. I have not made any changes in the code or configuration files. But it's taking more than 10hrs to train and still the training is not complete.

![image](https://user-images.githubusercontent.com/18366665/78150959-a8b99c00-7455-11ea-97df-c46f76f80542.png)

My GPU details are given below

![gpu_details](https://user-images.githubusercontent.com/18366665/78150833-727c1c80-7455-11ea-86d3-94c839875a98.png)

Can you confirm the amount of time it takes is fine or not.

**Comment by yourh** [comment]
It seems like there is something wrong with your PLT building and the training didn't start.  You can see that no process used your GPUs.
I just cloned the code and ran it on a 4 GPUs machine like yours, it works well like below:
![image](https://user-images.githubusercontent.com/28811637/78156563-8c2b5d00-7471-11ea-97ee-1ab64267aca1.png)

![image](https://user-images.githubusercontent.com/28811637/78157343-6ce0ff80-7472-11ea-83ea-73ec02c41813.png)

**Comment by pnjha** [comment]
I debugged and realized that the code is getting stuck in **_deepxml/tree.py_** 
 **if level == 0:
            while not os.path.exists('{}-Level-{}.npy'.format(self.groups_path,level)):
                time.sleep(30)**
Probably because file **"models/FastAttentionXML-Amazon-670K-Tree-0-cluster"** is not created.
Can you think about any reason for that?

**Comment by yourh** [comment]
This file is created by **deepxml/cluster.py**. I checked and ran the code from github more than one time. It works well.  Maybe you could check the code and data in your machine, debug your PLT buliding in **deepxml/cluster.py** and run it again.

**Comment by yourh** [comment]
> I debugged and realized that the code is getting stuck in **_deepxml/tree.py_**
> **if level == 0: while not os.path.exists('{}-Level-{}.npy'.format(self.groups_path,level)): time.sleep(30)**
> Probably because file **"models/FastAttentionXML-Amazon-670K-Tree-0-cluster"** is not created.
> Can you think about any reason for that?

This file is created by **deepxml/cluster.py**. I checked and ran the code from github more than one time. It works well. Maybe you could check the code and data in your machine, debug your PLT buliding in **deepxml/cluster.py** and run it again.

**Comment by pnjha** [comment]
The entire problem was related to CPU resources allocated. It does run as expected when I increased CPU resources to 16 cores. Thanks for your help.
