### ISSUE TITLE
Troubleshooting with Amazon-670K

### ISSUE THREAD

**Issue by tangzhy** [yourh/AttentionXML#13]
I find that if I directly run scripts on EUR-Lex or Amazon-670K, it would raise errors w.r.t segment fault. I doubt the multiprocessing part might be related with this issue. So I slightly change the run_xml.sh like 

![截屏2020-05-25 下午2 43 17](https://user-images.githubusercontent.com/36271700/82785905-13a3b400-9e96-11ea-924a-b37d9bf5e109.png)

Finally it works on EUR-Lex data. But still got errors on Amazon-670K when clustering labels. The errors were as follows:

![截屏2020-05-25 下午2 44 54](https://user-images.githubusercontent.com/36271700/82786007-4d74ba80-9e96-11ea-93e3-5a1e9b208aa8.png)

My server has been well set with 2080 Ti Gpus. Is this error merely caused by the GPU memory limits? Or I can adapt the code to fix it further? 

and advice?

**Comment by yourh** [comment]
-t 0 1 2 means the first, the second and the third model, not the multiprocessing.
The error in your picture is out of gpu memory when training deep model, not about clustering labels.
I tried to run it on Amazon-670K with 4*1080Ti and it works well.
If you only have one or two GPUs, maybe you can use some tricks such as gradient accumulation or use a small scale model by modifying codes slightly.

**Comment by tangzhy** [comment]
Thanks, I've sent an email expecting more communication about the details. 
Zhengyang
