### ISSUE TITLE
where is PLT compression performed?

### ISSUE THREAD

**Issue by tangzhy** [yourh/AttentionXML#14]
I've taken a close look in the code when running experiments on Amazon-670k.

When FastAttentionXML is being trained, it seems that:
1. we first start partitioning labels using 2-means clustering in deepxml/cluster.py;
2. we second conduct level-wise training recursively mainly in deepxml/tree.py and models&networks;

I see nowhere the PLT compression operation is involved in the pipeline. Maybe I missed something?

**Comment by yourh** [comment]
Compression is in cluster.py . The tree generated by cluster.py is the compressed one.

**Comment by tangzhy** [comment]
Sorry I didn't get the mathematical relationship between the code and paper. Here's my understanding when walking through cluster.py.

```python
def build_tree_by_level(sparse_data_x, sparse_data_y, mlb, eps: float, max_leaf: int, levels: list, groups_path):

    """
    The following block sets up the data where 
    	sparse_x refers to bow features w.r.t the documents (say its shape: N x D);
    	sparse_y refers to binarized labels (say its shape: N x L).
    """
    sparse_x, sparse_labels = get_sparse_feature(sparse_data_x, sparse_data_y)
    sparse_y = mlb.transform(sparse_labels)

    """
    The follwing line yields features for labels by matrix operation (say its shape: L x D).
    """
    labels_f = normalize(csr_matrix(sparse_y.T) @ csc_matrix(sparse_x))

    levels, q = [2**x for x in levels], None
    for i in range(len(levels)-1, -1, -1):
        if os.path.exists(F'{groups_path}-Level-{i}.npy'):
            labels_list = np.load(F'{groups_path}-Level-{i}.npy')
            q = [(labels_i, labels_f[labels_i]) for labels_i in labels_list]
            break
    if q is None:
        q = [(np.arange(labels_f.shape[0]), labels_f)]

    """
    The follwing block performs balanced 2-means clustering on 'labels_f' recursively.
    During which, if the number of clusters hits what we defined in 'levels', we save that for later use.
    """
    while q:
        labels_list = np.asarray([x[0] for x in q])
        assert sum(len(labels) for labels in labels_list) == labels_f.shape[0]
        if len(labels_list) in levels:
            level = levels.index(len(labels_list))
            logger.info(F'Finish Clustering Level-{level}')
            np.save(F'{groups_path}-Level-{level}.npy', np.asarray(labels_list))
        else:
            logger.info(F'Finish Clustering {len(labels_list)}')
        next_q = []
        for node_i, node_f in q:
            if len(node_i) > max_leaf:
                next_q += list(split_node(node_i, node_f, eps))
        q = next_q
    logger.info('Finish Clustering')
```

My concerns are: 
1. In the paper, we introduce the marginal probability for each node. I'm a bit lost how to relate that with the code.
2. The compression involves 3 steps, which are 

> (1) choose c-th ancestor nodes or the root as S_h.
> (2) remove nodes between S_{h_1} and S_h
> (3) reset nodes in S_h as parents

What do c-th ancestor nodes mean? I'm also lost with that, and therefore cannot figure out how T_1 is generated based on T_0.

3. I'm trying to adapt the code into my own experiments. I've trained embeddings of labels in my own way. May I replace the whole block which uses bow features of documents and binarized labels to build features for each label. In other words, I want to replace the `label_f` directly with my own embeddings and move on. Any advice?

**Comment by yourh** [comment]
I don't really understand your questions and I recived your email and added your wechat.
