### ISSUE TITLE
.npy file 

### ISSUE THREAD

**Issue by jeeveshkataria** [yourh/AttentionXML#17]
Sir, 
During preprocess
how is 
--vocab-path data/EUR-Lex/vocab.npy \
--emb-path data/EUR-Lex/emb_init.npy \ exist>
when we download the data set it does not have these two files.
please guide

**Comment by yourh** [comment]
These two files are created by preprocess.py.

**Comment by jeeveshkataria** [comment]
Thanks, Actually I am trying to replace BiLSTM with other models like Transformer  to know the change,
If the model speeds up or degrade. and all such kind of analysis.
may you guide with this how can I do that, 
I read modules.py there you have mentioned about biLSTM code, may you guide how can I replace and change the embeddings

**Comment by yourh** [comment]
First, you need to use BERT's tokenize to preprocess the texts. And then you need to use BERT encoder instead of the embedding layer and BiLSTM in AttentionXML.
