### ISSUE TITLE
CUDA ERROR

### ISSUE THREAD

**Issue by jeeveshkataria** [yourh/AttentionXML#18]
hi sir 
![Screenshot from 2020-09-18 02-16-37](https://user-images.githubusercontent.com/9196394/93526477-223a3d80-f955-11ea-91a7-cb7c29bce53d.png)
while running code in colab at first time it got run , 
but without any changes when i run again it started showing error
please guide

**Comment by jeeveshkataria** [comment]
also as you are using pytorch version 1.0.1 so i downgrade the version of cuda to 9 , but still error persis in colab

**Comment by jeeveshkataria** [comment]
https://drive.google.com/drive/folders/1kaSBip59wRGcpt62EUDD8Z2zoZoUM22C?usp=sharing

**Comment by yourh** [comment]
I'm so sorry I have no idea about this error. I think it's the error of your cuda or cudnn library, not codes of AttentionXML.

**Comment by jeeveshkataria** [comment]
thankyou for making reply

**Comment by HMM2021** [comment]
I have the same issue did you resolve it?

**Comment by celsofranssa** [comment]
Hello, anyone who could solve this issue?
