### ISSUE TITLE
What is the class number of model for the leaf classify?

### ISSUE THREAD

**Issue by guotong1988** [yourh/AttentionXML#2]
Thank you.

**Comment by yourh** [comment]
It's the number of labels.

**Comment by guotong1988** [comment]
But the total label number is millions.

**Comment by guotong1988** [comment]
How do the model contain so many parameters?

**Comment by yourh** [comment]
Only parameters of attention is linear to the number of labels. The parameters of attention is hidden size of BiLSTM (1024) × the number of labels. So we can store the whole model on the memory of GPUs.
