### ISSUE TITLE
How to generate `train_v1.txt` for datasets such as Amazon-670k?

### ISSUE THREAD

**Issue by celsofranssa** [yourh/AttentionXML#32]
The dataset Amazon-670k config has an additional parameter: `sparse: data/Amazon-670k/train_v1.txt`, which is not generated from the `run_preprocess.sh` script. 

What is `train_v1.txt`, and how to generate it?

**Comment by yourh** [comment]
It's the file of the BOW feature provided by the dataset.

**Comment by celsofranssa** [comment]
I must generate this BOW feature for different training/testing splits since I am applying k-fold cross-validation. Therefore, please give me directions on how to generate it.

**Comment by yourh** [comment]
This file and the raw text file `data/Amazon-670K/train_texts.txt` are corresponding so you can just use the same partition on these files.

**Comment by celsofranssa** [comment]
> This file and the raw text file `data/Amazon-670K/train_texts.txt` are corresponding so you can just use the same partition on these files.

And how could I do the same to the other folds?

**Comment by celsofranssa** [comment]
I was able to generate this feature file by combining [TfidfVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html) and dumping it in [svmlight](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.dump_svmlight_file.html#sklearn.datasets.dump_svmlight_file) format. I hope that's correct.
