### ISSUE TITLE
这是什么神奇项目，整个项目代码就差全部重构了，依然无法完整复现，真的是醉了，好奇作者在哪家公司？

### ISSUE THREAD

**Issue by runningabcd** [yourh/AttentionXML#37]
这个项目是为了论文写的吗？

真实醉了？

实话实说，有点拉胯，唉

**Comment by yourh** [comment]
这么多之后引用的文章的都跑成功了，包括当时文章的reviewer也都跑成功了，有没有可能是你自己太菜了呢，好奇你这么菜哪家公司能要你？

**Comment by runningabcd** [comment]
> 这么多之后引用的文章的都跑成功了，包括当时文章的reviewer也都跑成功了，有没有可能是你自己太菜了呢，好奇你这么菜哪家公司能要你？

对对对，我就是那种菜鸟中的菜鸟，你多看看你的代码逻辑吧

**Comment by runningabcd** [comment]
各位有中文语料需要基于这个模型训练的，请联系我，本人花了一个多小时，终于完成这个项目的全部重构，支持中文语料，支持 word2vector、glove、roberta向量输入

**Comment by runningabcd** [comment]
这个项目大家就别看了，代码确实有点辣眼睛，不过作者的开源精神，值得鼓励，但是是不是也得听下别人的建议，写的不好就是不好

**Comment by yourh** [comment]
> > 这么多之后引用的文章的都跑成功了，包括当时文章的reviewer也都跑成功了，有没有可能是你自己太菜了呢，好奇你这么菜哪家公司能要你？
> 
> 对对对，我就是那种菜鸟中的菜鸟，你多看看你的代码逻辑吧

你本来就是个菜鸟中的菜鸟，这代码本来就可以直接跑，大家都可以跑，就你复现不出来，难道不是你菜吗？
复现不复现和代码逻辑有什么关系？就问你能不能跑出来，不能跑出来就是你菜。
再说，代码什么逻辑问题你说啊，不愧是菜，张嘴就来。

**Comment by yourh** [comment]
> 各位有中文语料需要基于这个模型训练的，请联系我，本人花了一个多小时，终于完成这个项目的全部重构，支持中文语料，支持 word2vector、glove、roberta向量输入

> 这个项目大家就别看了，代码确实有点辣眼睛，不过作者的开源精神，值得鼓励，但是是不是也得听下别人的建议，写的不好就是不好

不看我的看你的，那你倒是开源呐，把你”不辣眼睛“的大作展现出来啊，东西呢？
还支持换其他向量的输入，这代码换词向量输入换不了？别人怎么都能搞定呢？
还联系你，真逗，你写的好，你写的最好了，就是给你一个别人都跑得出来的代码你就是跑不出来。
别一天天学两天编程就看谁都不顺眼，好好去学习吧，菜鸟。

**Comment by yourh** [comment]
> 这个项目大家就别看了，代码确实有点辣眼睛，不过作者的开源精神，值得鼓励，但是是不是也得听下别人的建议，写的不好就是不好

还”是不是也得听下别人的建议“，你建议什么了，你这个菜鸡除了不懂装懂上来就喷让后装个大B你建议什么了？我跑来听你一个代码都跑不清楚的文盲外行就会装B的喷子菜鸟的建议，你觉得合适吗？
