### ISSUE TITLE
What kind of dataset is better for AttentionXML

### ISSUE THREAD

**Issue by guotong1988** [yourh/AttentionXML#6]
I train AttentionXML on my Chinese dataset with average 20 sentence length and 150 classes.
The result is same to TextCNN.
Thank you!
@yourh

**Comment by yourh** [comment]
I think datasets with longer texts and more labels will be better by using RNN and attention. In fact, you can see that the performances of dataset RCV1 with only 103 labels are almost the same for XML methods such as DiSMEC, Parabel, PfastreXML, AnnexML and XML-CNN. But performances of these methods are totally different on other larger datasets.

**Comment by guotong1988** [comment]
Thank you. 
A little other question is that why longer text is better for RNN?
I hear that RNN does not remember long text.

**Comment by yourh** [comment]
RNN can capture the long-term dependency of inputs.
