### ISSUE TITLE
What is the content of the train_v1.txt file?

### ISSUE THREAD

**Issue by Cppowboy** [yourh/AttentionXML#7]
What is the content of the train_v1.txt file? How can I get the train_v1.txt file of my own dataset?
It seems that the train_v1.txt file contains a sparse matrix X and Y, and X is the bow feature of each instance. But why the vocab size is different from the vocab.npy?

**Comment by yourh** [comment]
The content of file train_v1.txt is totally the same as BOW feature provided by XMLRepository. We just deleted the first line about the number of samples, features and labels. I guess it's TFIDF feature. You can generate BOW feature for your own dataset by yourself.

**Comment by HMM2021** [comment]
is it necessary tf-idf, because it is not mentioned in the article . I tought that it's just tokenized text and label ids?
