### ISSUE TITLE
What's the difference between AttentionXML and fastAttentionXML?

### ISSUE THREAD

**Issue by MaYB2333** [yourh/AttentionXML#8]
Hi yourh !

    I find 2 models in this repo, AttentionXML and fastAttentionXML, the latter of which seems not occurred in your paper. Also, I can't find where the PLT module is used in AttentionXML. Could you tell me the difference between these two models, and, where is the PLT modules in AttentionXML?

Thank you very much!

**Comment by yourh** [comment]
FastAttentionXML is the AttentionXML with PLT.

**Comment by MaYB2333** [comment]
Thank you very much, so how can I run FastAttention on Wiki10-31K dataset? Seemingly there's no ['train']['sparse'] file.

**Comment by yourh** [comment]
You can download it from XMLRepository.

**Comment by MaYB2333** [comment]
I see, Thank you very much!
