### ISSUE TITLE
bert+label wise attention network?

### ISSUE THREAD

**Issue by brotherb** [yourh/AttentionXML#9]
Have you tried to replace bi-lstm with bert as encoder?

**Comment by yourh** [comment]
Yes. The performance will be improved but the training speed is slow.

**Comment by brotherb** [comment]
> Yes. The performance will be improved but the training speed is slow.

how much is the improvements? I find it really hard to improve. After carefully tuned the hyper parameters, bert just catch up with attentionxml。Any tricks needed？

**Comment by yourh** [comment]
We only tried it a little without any tricks. It's only a slight improvement on some datasets.

**Comment by simonlevine** [comment]
Hi, will you release the code where BERT is the replacement encoder? Thanks!
